import 'package:hive/hive.dart';

part 'time_and_date.g.dart';

@HiveType(typeId: 8)
class TimeAndDate {
  @HiveField(0)
  late List<String> nameRus = [
    "Месяц",
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь",
    "Год",
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
    "Воскресенье",
    "Летнее время",
    "Местное время",
    "Сколько времени?",
    "Сейчас 10 часов",
    "9 часов 30 минут (пол десятого)",
    "Без пятнадцати 12",
    "Времена года",
    "Зима",
    "Весна",
    "Лето",
    "Осень",
    "Вчера",
    "Сегодня",
    "Завтра",
    "Послезавтра",
    "Сегодня утром",
    "Давно",
    "Недавно",
    "В последнее время",
    "Сейчас",
    "Мне пора!",
  ];

  @HiveField(1)
  late List<String> nameTurk = [
    "Aý",
    "Ýanwar",
    "Fewral",
    "Mart",
    "Aprel",
    "Maý",
    "Iýun",
    "Iýul",
    "Awgust",
    "Sentýabr",
    "Oktýabr",
    "Noýabr",
    "Dekabr",
    "Ýyl",
    "Duşenbe",
    "Sişenbe",
    "Çarşenbe",
    "Penşenbe",
    "Anna",
    "Şenbe",
    "Ýekşenbe",
    "Tomus wagty",
    "Ýerli wagt",
    "Sagat näçe?",
    "Häzir sagat 10",
    "9 sagat 30 minut (10-nyň ýary)",
    "15 minudy kem 12",
    "Ýyl pasyllary",
    "Gyş",
    "Bahar",
    "Tomus",
    "Güýz",
    "Düýn, öten gün",
    "Şu gün",
    "Ertir",
    "Birigün",
    "Şügün irden",
    "Öň, bireýýäm",
    "Ýaňy-ýakynda, golaýda",
    "Soňky wagtda",
    "Häzir",
    "Meniň gitmeli wagtym boldy!",
  ];
}
